schema_version = "1.0.0"

id = "blender_shelf"
version = "0.2.2"
name = "BlenderShelf"
tagline = "Custom button shelf for the 3D Viewport, UV and node editors"
maintainer = "DenisZakharov"
type = "add-on"

website = "https://blendershelf.github.io/BlenderShelf/"

tags = ["3D View", "User Interface"]

license = [
  "SPDX:GPL-3.0-or-later",
]

blender_version_min = "4.2.0"

[permissions]
network = "Checks blendershelf.github.io for the latest release version"
